# Configuration for cargo-deny

[licenses]
# Allow these licenses
allow = [
    "MIT",
    "Apache-2.0",
    "Apache-2.0 WITH LLVM-exception",
    "BSD-2-Clause",
    "BSD-3-Clause",
    "ISC",
    "Unicode-DFS-2016",
]
# Deny these licenses
deny = [
    "GPL-3.0",
    "AGPL-3.0",
]
# Confidence threshold for detecting a license from a license text.
# Defaults to 0.8 (80%), so we need to be quite confident.
confidence-threshold = 0.8

[bans]
# Lint level for when multiple versions of the same crate are detected
multiple-versions = "warn"
# Lint level for when a crate version requirement is `*`
wildcards = "allow"
# Bans certain crates from being used
deny = [
    # Bans specific crates that might be problematic
]

[advisories]
# Lint level for security vulnerabilities
vulnerability = "deny"
# Lint level for crates that have been yanked from their source registry
yanked = "warn"
# Lint level for crates with security notices.
notice = "warn"
# Ignore advisories for the given IDs
ignore = []
